// <auto-generated />
using System;
using Mfc.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mfc.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MfcDbContext))]
    [Migration("20260808073351_InventorySnapshotSchema")]
    partial class InventorySnapshotSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mfc.Infrastructure.Persistence.Entities.AuditEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<byte[]>("EventHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<byte[]>("PreviousEventHash")
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("EventHash")
                        .IsUnique();

                    b.HasIndex("OccurredAtUtc");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("Mfc.Infrastructure.Persistence.Entities.CaptureOperationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("text");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<short>("TargetType")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("RequestedBy", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("uq_capture_operation_idempotency");

                    b.ToTable("capture_operations", (string)null);
                });

            modelBuilder.Entity("Mfc.Infrastructure.Persistence.Entities.ControllerInstanceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicationVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ProcessId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("HostName");

                    b.ToTable("controller_instances", (string)null);
                });

            modelBuilder.Entity("Mfc.Infrastructure.Persistence.Entities.DeviceConnectionProfileEntity", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("CaProfileRef")
                        .HasColumnType("text");

                    b.Property<int>("CommandTimeoutMs")
                        .HasColumnType("integer");

                    b.Property<int>("ConnectTimeoutMs")
                        .HasColumnType("integer");

                    b.Property<Guid>("EncryptedSecretId")
                        .HasColumnType("uuid");

                    b.Property<long>("MaxResponseBytes")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("PinnedSpkiSha256")
                        .HasColumnType("bytea");

                    b.Property<long>("RowVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.Property<short>("TrustMode")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DeviceId");

                    b.HasIndex("EncryptedSecretId");

                    b.ToTable("device_connection_profiles", null, t =>
                        {
                            t.HasCheckConstraint("ck_connection_command_timeout", "\"CommandTimeoutMs\" BETWEEN 1000 AND 120000");

                            t.HasCheckConstraint("ck_connection_connect_timeout", "\"ConnectTimeoutMs\" BETWEEN 1000 AND 30000");

                            t.HasCheckConstraint("ck_connection_max_response", "\"MaxResponseBytes\" BETWEEN 1048576 AND 268435456");

                            t.HasCheckConstraint("ck_connection_row_version", "\"RowVersion\" > 0");

                            t.HasCheckConstraint("ck_connection_spki", "\"PinnedSpkiSha256\" IS NULL OR octet_length(\"PinnedSpkiSha256\") = 32");

                            t.HasCheckConstraint("ck_connection_username", "length(\"Username\") BETWEEN 1 AND 64");
                        });
                });

            modelBuilder.Entity("Mfc.Infrastructure.Persistence.Entities.DeviceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid?>("LastCompletedCaptureId")
                        .HasColumnType("uuid");

                    b.Property<short?>("LastSupportState")
                        .HasColumnType("smallint");

                    b.Property<string>("ManagementHost")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("ManagementHostKind")
                        .HasColumnType("smallint");

                    b.Property<int>("ManagementPort")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(8729);

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<long>("RowVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.HasIndex("ManagementHost", "ManagementPort")
                        .IsUnique()
                        .HasDatabaseName("uq_devices_active_endpoint")
                        .HasFilter("\"Enabled\" = TRUE");

                    b.ToTable("devices", null, t =>
                        {
                            t.HasCheckConstraint("ck_devices_name", "length(btrim(\"DisplayName\")) BETWEEN 1 AND 128");

                            t.HasCheckConstraint("ck_devices_port", "\"ManagementPort\" BETWEEN 1 AND 65535");

                            t.HasCheckConstraint("ck_devices_row_version", "\"RowVersion\" > 0");
                        });
                });

            modelBuilder.Entity("Mfc.Infrastructure.Persistence.Entities.EncryptedSecretEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<byte[]>("Ciphertext")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RotatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("WrappedDek")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.ToTable("encrypted_secrets", (string)null);
                });

            modelBuilder.Entity("Mfc.Infrastructure.Persistence.Entities.IdempotencyRecordEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<byte[]>("RequestHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ResponseRef")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Key");

                    b.HasIndex("Actor", "Operation", "Key")
                        .IsUnique();

                    b.ToTable("idempotency_records", (string)null);
                });

            modelBuilder.Entity("Mfc.Infrastructure.Persistence.Entities.NodeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("DeclaredKind")
                        .HasColumnType("smallint");

                    b.Property<short>("DeclaredUplinkMode")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("RowVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SiteId", "Name")
                        .IsUnique()
                        .HasDatabaseName("uq_nodes_site_name");

                    b.ToTable("nodes", null, t =>
                        {
                            t.HasCheckConstraint("ck_nodes_name", "length(btrim(\"Name\")) BETWEEN 1 AND 128");

                            t.HasCheckConstraint("ck_nodes_row_version", "\"RowVersion\" > 0");
                        });
                });

            modelBuilder.Entity("Mfc.Infrastructure.Persistence.Entities.SchemaMetadataEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Key");

                    b.ToTable("schema_metadata", (string)null);
                });

            modelBuilder.Entity("Mfc.Infrastructure.Persistence.Entities.SiteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("RowVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_sites_code");

                    b.ToTable("sites", null, t =>
                        {
                            t.HasCheckConstraint("ck_sites_code", "\"Code\" ~ '^[A-Z][A-Z0-9_-]{1,31}$'");

                            t.HasCheckConstraint("ck_sites_name", "length(btrim(\"Name\")) BETWEEN 1 AND 128");

                            t.HasCheckConstraint("ck_sites_row_version", "\"RowVersion\" > 0");
                        });
                });

            modelBuilder.Entity("Mfc.Infrastructure.Persistence.Entities.SnapshotCaptureEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<short>("AttemptCount")
                        .HasColumnType("smallint");

                    b.Property<byte[]>("CapabilityHash")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("CapabilityPayloadHash")
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("CaptureCompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CaptureStartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("CompatibilityMaterialHash")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("CompatibilityPayloadHash")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("ConfigurationHash")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("ConfigurationPayloadHash")
                        .HasColumnType("bytea");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("text");

                    b.Property<string>("ErrorDetailsJson")
                        .HasColumnType("jsonb");

                    b.Property<byte[]>("ObservationHash")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("ObservationPayloadHash")
                        .HasColumnType("bytea");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("Pass1CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("Pass2CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RawPayloadHash")
                        .HasColumnType("bytea");

                    b.Property<string>("SectionResultsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<byte[]>("SnapshotHash")
                        .HasColumnType("bytea");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("OperationId", "DeviceId")
                        .IsUnique()
                        .HasDatabaseName("uq_snapshot_capture_device_operation");

                    b.ToTable("snapshot_captures", (string)null);
                });

            modelBuilder.Entity("Mfc.Infrastructure.Persistence.Entities.SnapshotPayloadEntity", b =>
                {
                    b.Property<byte[]>("PayloadHash")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("CompressedPayload")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<short>("Compression")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("PayloadKind")
                        .HasColumnType("smallint");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer");

                    b.Property<long>("UncompressedSize")
                        .HasColumnType("bigint");

                    b.HasKey("PayloadHash");

                    b.ToTable("snapshot_payloads", null, t =>
                        {
                            t.HasCheckConstraint("ck_snapshot_payload_hash", "octet_length(\"PayloadHash\") = 32");

                            t.HasCheckConstraint("ck_snapshot_payload_size", "\"UncompressedSize\" > 0 AND \"UncompressedSize\" <= 268435456");
                        });
                });

            modelBuilder.Entity("Mfc.Infrastructure.Persistence.Entities.DeviceConnectionProfileEntity", b =>
                {
                    b.HasOne("Mfc.Infrastructure.Persistence.Entities.DeviceEntity", null)
                        .WithOne()
                        .HasForeignKey("Mfc.Infrastructure.Persistence.Entities.DeviceConnectionProfileEntity", "DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mfc.Infrastructure.Persistence.Entities.EncryptedSecretEntity", null)
                        .WithMany()
                        .HasForeignKey("EncryptedSecretId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mfc.Infrastructure.Persistence.Entities.DeviceEntity", b =>
                {
                    b.HasOne("Mfc.Infrastructure.Persistence.Entities.NodeEntity", null)
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mfc.Infrastructure.Persistence.Entities.NodeEntity", b =>
                {
                    b.HasOne("Mfc.Infrastructure.Persistence.Entities.SiteEntity", null)
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mfc.Infrastructure.Persistence.Entities.SnapshotCaptureEntity", b =>
                {
                    b.HasOne("Mfc.Infrastructure.Persistence.Entities.DeviceEntity", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mfc.Infrastructure.Persistence.Entities.CaptureOperationEntity", null)
                        .WithMany()
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
