<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Mfc.Application\Mfc.Application.csproj" />
    <ProjectReference Include="..\Mfc.Domain\Mfc.Domain.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <RootNamespace>Mfc.Infrastructure</RootNamespace>
    <AssemblyName>Mfc.Infrastructure</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
</Project>
